"""added User role

Revision ID: 100bffe487a8
Revises: ea5bd9a527dd
Create Date: 2025-02-27 22:22:29.227447

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import ENUM


# revision identifiers, used by Alembic.
revision: str = "100bffe487a8"
down_revision: Union[str, None] = "ea5bd9a527dd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    userrole_enum = ENUM("USER", "ADMIN", name="userrole", create_type=True)
    op.create_table(
        "users",
        sa.Column("role", userrole_enum, nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "role")
    # ### end Alembic commands ###
