"""add to model User filed confirmed

Revision ID: 26ddc3f525f6
Revises: f70bd2d7a464
Create Date: 2025-02-09 13:24:02.788700

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26ddc3f525f6'
down_revision: Union[str, None] = 'f70bd2d7a464'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
